DATE:=$(shell date +%Y_%m_%d)
PWD:=$(shell pwd)

all:
	wget -N https://www.gstatic.com/covid19/mobility/Global_Mobility_Report.csv

	cp Global_Mobility_Report.csv Global_Mobility_Report.csv_${DATE}.csv

